Add ability to use with callback or event, as needed - fix #38
alexgibson/shake.js pull request #39
Opened 2016-11-07 07:42 UTC by iJungleboy

The new implementation allows the dev to add a callback: function. If that exists, the event will not bubble through the event system but only call the callback. 

This makes certain things cleaner and also prevents the danger of multiple executions, if Shake() was initialized more than once.

2016-11-07 08:05 UTC, alexgibson requested changes

2016-11-07 08:05 UTC, alexgibson commented on bower.json
> +        "name": "Alex Gibson & Daniel Mettler",
Sorry, but just because you've contributed to the project doesn't give you author rights. You just join the list of contributors who have already made patches.

2016-11-07 08:05 UTC, alexgibson commented on shake.js
> +        if(!this.options.callback) {
This isn't quite the API I want to move to in the future. I'd like to move to callback only.

2016-11-07 08:05 UTC, alexgibson commented on bower.json
> +    "version": "1.2.3",
This should probably be a major version change as opposed to a point release.

2016-11-07 08:07 UTC, alexgibson requested changes

2016-11-07 08:07 UTC, alexgibson commented on shake.js
> +
Remove unnecessary whitespace

2016-11-07 08:08 UTC, alexgibson requested changes

2016-11-07 08:08 UTC, alexgibson commented on shake.js
> +            callback: null // optional callback - will only be used if provided, otherwise generate event // function() {}//default interval between events
The comments have got a bit messed up here

2016-11-07 08:10 UTC, alexgibson commented
You also need to update `package.json` and update the documentation in `README.md`

2016-11-07 08:17 UTC, alexgibson commented
Updating the example in `index.html` would also be useful, thanks.

2016-11-07 08:21 UTC, alexgibson commented on bower.json
> +    "version": "1.2.3",
If we move to callback only I think this should probably be `1.3.0`

2016-11-07 13:27 UTC, iJungleboy commented on bower.json
> +        "name": "Alex Gibson & Daniel Mettler",
no problem :)

2016-11-07 13:28 UTC, iJungleboy commented on shake.js
> +        if(!this.options.callback) {
that would be ok for me, but would be a full breaking change then.

2016-11-07 13:29 UTC, iJungleboy commented
If you change it to only having a callback (which I think is a good idea) I believe you should make it a 2.0 because it's a breaking change - so semantic versioning would require a full version increase. What do you think?

BTW: I agree with your changes, but I've never done such a request-changes cycle. how do I integrate these back into my push?

2016-11-07 13:31 UTC, alexgibson commented
Ok let's change it to 2.0. Just add another commit to your branch and GitHub will pick up the changes here. Thanks

2016-11-07 13:42 UTC, iJungleboy commented on bower.json
> +    "version": "1.2.3",
as discussed, going to 2.0.0

2016-11-07 13:53 UTC, iJungleboy commented
BTW: do you have a good way of testing this stuff on the desktop? testing feels a bit messy ATM.

2016-11-07 13:57 UTC, alexgibson commented
My current method is just to fire up a local web server (e.g python simple server) and aim a load of mobile devices at it. It's not ideal, but this is the kind of API that's hard to simulate.

2016-11-07 14:02 UTC, iJungleboy commented
IMHO I just implemented everything

2016-11-07 14:31 UTC, alexgibson requested changes
Looking good, just a fix things to fix up. The main thing I think we need to do is make the callback required instead of optional.

2016-11-07 14:31 UTC, alexgibson commented on README.md
> +function myStuffWhenItShakes() {
Please change this to `shakeEventDidOccur`, to match the demo example.

2016-11-07 14:31 UTC, alexgibson commented on README.md
> +    callback: myStuffWhenItShakes   // optional but important, without it, shakes will only cause console-log entries
I'd rather make this strictly required, else it will just eat someone's battery silently. I'd even go so far as to say if this callback is not supplied, we should throw an error when calling `start()` to make it obvious what is wrong.

2016-11-07 14:31 UTC, alexgibson commented on shake.js
> +                    console.log("shake event without callback detected");
Please remove `console.log();` from production code, thanks.

2016-11-07 14:31 UTC, alexgibson commented on shake.js
> +            callback: null // callback - will only be used if provided, otherwise generate event // function() {}//default interval between events
These comments still need fixing.

2016-11-07 14:31 UTC, alexgibson commented on shake.js
> +
Nit: remove empty whitespace

2016-11-07 14:31 UTC, alexgibson commented on shake.js
> +                // once triggered, execute  the callback
Nit: extra space here between `excecute` and `the`.

2016-11-07 14:48 UTC, alexgibson requested changes

2016-11-07 14:48 UTC, alexgibson commented on README.md
> +<script>
I think we could also lose the `<script>` tags here. It implies the function should be global, which is not really required.

2016-11-07 14:48 UTC, alexgibson commented on README.md
> +Now, create your custom code
Please change this to `Now, create your callback function for when a shake occurs:`

2016-11-07 14:48 UTC, alexgibson commented on README.md
> +Next, create a new Shake instance:
Please change this to `Next, create a new Shake instance and assign it the callback we created previously:`

2016-11-23 19:21 UTC, alexgibson commented
Friendly ping there are still outstanding comments here that need addressing.

2016-11-24 13:55 UTC, iJungleboy commented
Sorry, have too much on my desk right now, can't prioritize this :(

2016-11-24 14:36 UTC, closed without merging

2016-11-24 14:36 UTC, alexgibson commented
Feel free to reopen if you even want to finish this.